# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
  - main

# self hosted Linux machine
pool:
  name: Default

# Verify Terraform version
steps:
- script: |
    terraform version
  displayName: "Verify Terraform"

# terraform init
- task: TerraformTask@5
  displayName: "Terraform Init-QA"
  inputs:
    provider: azurerm
    command: init
    commandOptions: '-reconfigure'
    workingDirectory: $(Build.SourcesDirectory)/templetes
    backendServiceArm: 'new_sv_connection'
    backendAzureRmResourceGroupName: 'test-rg'
    backendAzureRmStorageAccountName: 'testaccountsampltf'
    backendAzureRmContainerName: 'sampletfcontainer'
    backendAzureRmKey: "QA/terraform.tfstate"


# terraform plan
- task: TerraformTask@5
  displayName: "Terraform Plan-QA"
  inputs:
    provider: azurerm
    command: plan
    workingDirectory: $(Build.SourcesDirectory)/templetes
    environmentServiceNameAzureRM: 'new_sv_connection'

# terraform apply
- task: TerraformTask@5
  displayName: "Terraform Apply-QA"
  inputs:
    provider: azurerm
    command: apply
    workingDirectory: $(Build.SourcesDirectory)/templetes
    environmentServiceNameAzureRM: 'new_sv_connection'
    commandOptions: '--auto-approve'

